# Generated by Django 3.1 on 2021-01-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210128_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='userId',
        ),
    ]
